import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSchoolExtendedFields1778229503319 implements MigrationInterface {
    name = 'AddSchoolExtendedFields1778229503319'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "profiles_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "timetable_slots_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "timetable_slots_academic_year_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "timetable_slots_course_assignment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_class_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "specialties" DROP CONSTRAINT "specialties_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "specialties" DROP CONSTRAINT "specialties_program_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "program_levels" DROP CONSTRAINT "program_levels_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "program_levels" DROP CONSTRAINT "program_levels_program_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_started_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_ended_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_course_assignment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "sessions_timetable_slot_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "schools_organization_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "school_memberships_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "school_memberships_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "organizations_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "organization_memberships_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "organization_memberships_organization_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "staff_invitations_invited_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "staff_invitations_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" DROP CONSTRAINT "staff_invitations_department_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" DROP CONSTRAINT "import_jobs_initiated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" DROP CONSTRAINT "import_jobs_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "refresh_tokens_replaced_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_scope_organization_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_scope_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_marked_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "semesters" DROP CONSTRAINT "semesters_academic_year_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_department_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "departments_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_department_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_lecturer_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_academic_year_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_class_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "classes_school_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "classes_academic_year_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "classes_program_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "classes_specialty_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP CONSTRAINT "academic_years_school_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_timetable_slots_assignment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_specialties_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_specialties_school"`);
        await queryRunner.query(`DROP INDEX "public"."idx_program_levels_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_school_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_assignment"`);
        await queryRunner.query(`DROP INDEX "public"."idx_school_memberships_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_scope"`);
        await queryRunner.query(`DROP INDEX "public"."idx_org_memberships_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_staff_invites_pending"`);
        await queryRunner.query(`DROP INDEX "public"."idx_import_jobs_school_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_tokens_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_scope_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attendance_school_session"`);
        await queryRunner.query(`DROP INDEX "public"."idx_academic_years_school"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "timetable_slots_day_of_week_check"`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" DROP CONSTRAINT "timetable_slots_check"`);
        await queryRunner.query(`ALTER TABLE "program_levels" DROP CONSTRAINT "program_levels_level_check"`);
        await queryRunner.query(`ALTER TABLE "semesters" DROP CONSTRAINT "semesters_check"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_duration_years_check"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_unit_load_check"`);
        await queryRunner.query(`ALTER TABLE "academic_years" DROP CONSTRAINT "academic_years_check"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "students_school_id_matric_no_key"`);
        await queryRunner.query(`ALTER TABLE "specialties" DROP CONSTRAINT "specialties_school_id_code_key"`);
        await queryRunner.query(`ALTER TABLE "program_levels" DROP CONSTRAINT "program_levels_program_id_level_key"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "schools_organization_id_code_key"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "school_memberships_school_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_school_id_role_key"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "organization_memberships_organization_id_user_id_key"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_session_id_student_id_key"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_school_id_code_key"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "departments_school_id_code_key"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_school_id_code_key"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "course_assignments_school_id_course_id_class_id_lecturer_us_key"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "classes_school_id_academic_year_id_name_key"`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "address" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "website" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "logo_url" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "timezone" text`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "session_duration_minutes" integer`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "late_threshold_minutes" integer`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "require_geo_checkin" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "schools" ADD "allow_late_checkin" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TYPE "public"."session_status" RENAME TO "session_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."sessions_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "public"."sessions_status_enum" USING "status"::"text"::"public"."sessions_status_enum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."session_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."school_status" RENAME TO "school_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."schools_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" TYPE "public"."schools_status_enum" USING "status"::"text"::"public"."schools_status_enum"`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."school_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."user_roles_role_enum" AS ENUM('owner', 'admin', 'director', 'hod', 'lecturer', 'student', 'guardian', 'follower')`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" TYPE "public"."user_roles_role_enum" USING "role"::"text"::"public"."user_roles_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."membership_role" RENAME TO "membership_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."organization_memberships_role_enum" AS ENUM('owner', 'member', 'follower')`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ALTER COLUMN "role" TYPE "public"."organization_memberships_role_enum" USING "role"::"text"::"public"."organization_memberships_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."membership_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."staff_invitations_role_enum" AS ENUM('owner', 'admin', 'director', 'hod', 'lecturer', 'student', 'guardian', 'follower')`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "role" TYPE "public"."staff_invitations_role_enum" USING "role"::"text"::"public"."staff_invitations_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TYPE "public"."invitation_status" RENAME TO "invitation_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."staff_invitations_status_enum" AS ENUM('pending', 'processing', 'accepted', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" TYPE "public"."staff_invitations_status_enum" USING "status"::"text"::"public"."staff_invitations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."invitation_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."import_job_status" RENAME TO "import_job_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."import_jobs_status_enum" AS ENUM('created', 'validating', 'ready', 'committing', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" TYPE "public"."import_jobs_status_enum" USING "status"::"text"::"public"."import_jobs_status_enum"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "public"."import_job_status_old"`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status" RENAME TO "attendance_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ALTER COLUMN "status" TYPE "public"."attendance_records_status_enum" USING "status"::"text"::"public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status_old"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ALTER COLUMN "marked_at" DROP DEFAULT`);
        await queryRunner.query(`CREATE INDEX "IDX_b1df75d23a9799d54f79e0155d" ON "timetable_slots" ("course_assignment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cb96d1f6f37a3edb50ee77722" ON "sessions" ("course_assignment_id", "scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a48f44bc3bf414f5b8deb1806" ON "sessions" ("school_id", "scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_767c1a9d6f281077a8c267328c" ON "import_jobs" ("school_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0c1682da0e72bde5a429534bdb" ON "audit_logs" ("scope_school_id", "occurred_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2894093810cefc006774ef2dba" ON "attendance_records" ("school_id", "session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b293eb7909d2a3aae86c438071" ON "academic_years" ("school_id") `);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "UQ_0bb6314b02e6167ae6269ba694c" UNIQUE ("school_id", "matric_no")`);
        await queryRunner.query(`ALTER TABLE "specialties" ADD CONSTRAINT "UQ_633a6ebc39f9a0ddbaa38f535f0" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "program_levels" ADD CONSTRAINT "UQ_32128d4a37b927a0ab6753b3594" UNIQUE ("program_id", "level")`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "UQ_dc8fd03e830c19c404a7336edbd" UNIQUE ("organization_id", "code")`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "UQ_c9e891b94744eb4ec7b22327c61" UNIQUE ("school_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "UQ_262d02a9f86b6834273a8e509d2" UNIQUE ("user_id", "school_id", "role")`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "UQ_caa73db1b161fa6b3a042290fe7" UNIQUE ("organization_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "UQ_0a47908a8a405f82595b678f9e1" UNIQUE ("session_id", "student_id")`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "UQ_321a396299dc3fa06a51132cfa0" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "UQ_f33a5c6f314d9d62d92ad14ce20" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "UQ_ab58f0dcc8ba56621a91942397c" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "UQ_fd2a00d1ead8371a8f9bd5e582b" UNIQUE ("school_id", "course_id", "class_id", "lecturer_user_id", "academic_year_id")`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "UQ_2443c515ef3aac7ca2c5c02b734" UNIQUE ("school_id", "academic_year_id", "name")`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_8e520eb4da7dc01d0e190447c8e" FOREIGN KEY ("id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_8e520eb4da7dc01d0e190447c8e"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "UQ_2443c515ef3aac7ca2c5c02b734"`);
        await queryRunner.query(`ALTER TABLE "course_assignments" DROP CONSTRAINT "UQ_fd2a00d1ead8371a8f9bd5e582b"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "UQ_ab58f0dcc8ba56621a91942397c"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "UQ_f33a5c6f314d9d62d92ad14ce20"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "UQ_321a396299dc3fa06a51132cfa0"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "UQ_0a47908a8a405f82595b678f9e1"`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" DROP CONSTRAINT "UQ_caa73db1b161fa6b3a042290fe7"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "UQ_262d02a9f86b6834273a8e509d2"`);
        await queryRunner.query(`ALTER TABLE "school_memberships" DROP CONSTRAINT "UQ_c9e891b94744eb4ec7b22327c61"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "UQ_dc8fd03e830c19c404a7336edbd"`);
        await queryRunner.query(`ALTER TABLE "program_levels" DROP CONSTRAINT "UQ_32128d4a37b927a0ab6753b3594"`);
        await queryRunner.query(`ALTER TABLE "specialties" DROP CONSTRAINT "UQ_633a6ebc39f9a0ddbaa38f535f0"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "UQ_0bb6314b02e6167ae6269ba694c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b293eb7909d2a3aae86c438071"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2894093810cefc006774ef2dba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c1682da0e72bde5a429534bdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_767c1a9d6f281077a8c267328c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a48f44bc3bf414f5b8deb1806"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb96d1f6f37a3edb50ee77722"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1df75d23a9799d54f79e0155d"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ALTER COLUMN "marked_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status_old" AS ENUM('present', 'absent', 'late', 'excused')`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ALTER COLUMN "status" TYPE "public"."attendance_status_old" USING "status"::"text"::"public"."attendance_status_old"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."attendance_status_old" RENAME TO "attendance_status"`);
        await queryRunner.query(`CREATE TYPE "public"."import_job_status_old" AS ENUM('created', 'validating', 'ready', 'committing', 'completed', 'failed')`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" TYPE "public"."import_job_status_old" USING "status"::"text"::"public"."import_job_status_old"`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "public"."import_jobs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."import_job_status_old" RENAME TO "import_job_status"`);
        await queryRunner.query(`CREATE TYPE "public"."invitation_status_old" AS ENUM('pending', 'processing', 'accepted', 'expired', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" TYPE "public"."invitation_status_old" USING "status"::"text"::"public"."invitation_status_old"`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."staff_invitations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invitation_status_old" RENAME TO "invitation_status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('owner', 'admin', 'director', 'hod', 'lecturer', 'student', 'guardian', 'follower')`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`DROP TYPE "public"."staff_invitations_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`CREATE TYPE "public"."membership_role_old" AS ENUM('owner', 'member', 'follower')`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ALTER COLUMN "role" TYPE "public"."membership_role_old" USING "role"::"text"::"public"."membership_role_old"`);
        await queryRunner.query(`DROP TYPE "public"."organization_memberships_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."membership_role_old" RENAME TO "membership_role"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('owner', 'admin', 'director', 'hod', 'lecturer', 'student', 'guardian', 'follower')`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`DROP TYPE "public"."user_roles_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`CREATE TYPE "public"."school_status_old" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" TYPE "public"."school_status_old" USING "status"::"text"::"public"."school_status_old"`);
        await queryRunner.query(`ALTER TABLE "schools" ALTER COLUMN "status" SET DEFAULT 'active'`);
        await queryRunner.query(`DROP TYPE "public"."schools_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."school_status_old" RENAME TO "school_status"`);
        await queryRunner.query(`CREATE TYPE "public"."session_status_old" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "public"."session_status_old" USING "status"::"text"::"public"."session_status_old"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'scheduled'`);
        await queryRunner.query(`DROP TYPE "public"."sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."session_status_old" RENAME TO "session_status"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "allow_late_checkin"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "require_geo_checkin"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "late_threshold_minutes"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "session_duration_minutes"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "website"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "classes_school_id_academic_year_id_name_key" UNIQUE ("school_id", "academic_year_id", "name")`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_school_id_course_id_class_id_lecturer_us_key" UNIQUE ("school_id", "course_id", "class_id", "lecturer_user_id", "academic_year_id")`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_school_id_code_key" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "departments_school_id_code_key" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_school_id_code_key" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_session_id_student_id_key" UNIQUE ("session_id", "student_id")`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_organization_id_user_id_key" UNIQUE ("organization_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_school_id_role_key" UNIQUE ("user_id", "school_id", "role")`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "school_memberships_school_id_user_id_key" UNIQUE ("school_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "schools_organization_id_code_key" UNIQUE ("organization_id", "code")`);
        await queryRunner.query(`ALTER TABLE "program_levels" ADD CONSTRAINT "program_levels_program_id_level_key" UNIQUE ("program_id", "level")`);
        await queryRunner.query(`ALTER TABLE "specialties" ADD CONSTRAINT "specialties_school_id_code_key" UNIQUE ("school_id", "code")`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_school_id_matric_no_key" UNIQUE ("school_id", "matric_no")`);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_check" CHECK ((start_date < end_date))`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_unit_load_check" CHECK ((unit_load > 0))`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_duration_years_check" CHECK ((duration_years > 0))`);
        await queryRunner.query(`ALTER TABLE "semesters" ADD CONSTRAINT "semesters_check" CHECK ((start_date < end_date))`);
        await queryRunner.query(`ALTER TABLE "program_levels" ADD CONSTRAINT "program_levels_level_check" CHECK ((level > 0))`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_check" CHECK ((start_time < end_time))`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_day_of_week_check" CHECK (((day_of_week >= 1) AND (day_of_week <= 7)))`);
        await queryRunner.query(`CREATE INDEX "idx_academic_years_school" ON "academic_years" ("school_id") `);
        await queryRunner.query(`CREATE INDEX "idx_attendance_school_session" ON "attendance_records" ("school_id", "session_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_scope_time" ON "audit_logs" ("scope_school_id", "occurred_at") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_tokens_user" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_import_jobs_school_status" ON "import_jobs" ("school_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_staff_invites_pending" ON "staff_invitations" ("school_id", "expires_at") WHERE (status = 'pending'::invitation_status)`);
        await queryRunner.query(`CREATE INDEX "idx_org_memberships_user" ON "organization_memberships" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_scope" ON "user_roles" ("user_id", "school_id") `);
        await queryRunner.query(`CREATE INDEX "idx_school_memberships_user" ON "school_memberships" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_assignment" ON "sessions" ("course_assignment_id", "scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "idx_sessions_school_date" ON "sessions" ("school_id", "scheduled_date") `);
        await queryRunner.query(`CREATE INDEX "idx_program_levels_program" ON "program_levels" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "idx_specialties_school" ON "specialties" ("school_id") `);
        await queryRunner.query(`CREATE INDEX "idx_specialties_program" ON "specialties" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "idx_timetable_slots_assignment" ON "timetable_slots" ("course_assignment_id") `);
        await queryRunner.query(`ALTER TABLE "academic_years" ADD CONSTRAINT "academic_years_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "classes_specialty_id_fkey" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "classes_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "classes_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "classes_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_assignments" ADD CONSTRAINT "course_assignments_lecturer_user_id_fkey" FOREIGN KEY ("lecturer_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "departments_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "semesters" ADD CONSTRAINT "semesters_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_marked_by_fkey" FOREIGN KEY ("marked_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_scope_school_id_fkey" FOREIGN KEY ("scope_school_id") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_scope_organization_id_fkey" FOREIGN KEY ("scope_organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_fkey" FOREIGN KEY ("actor_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_replaced_by_fkey" FOREIGN KEY ("replaced_by") REFERENCES "refresh_tokens"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "import_jobs" ADD CONSTRAINT "import_jobs_initiated_by_fkey" FOREIGN KEY ("initiated_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "staff_invitations_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "staff_invitations_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_invitations" ADD CONSTRAINT "staff_invitations_invited_by_fkey" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_memberships" ADD CONSTRAINT "organization_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "organizations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "school_memberships_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_memberships" ADD CONSTRAINT "school_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "schools_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_timetable_slot_id_fkey" FOREIGN KEY ("timetable_slot_id") REFERENCES "timetable_slots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_course_assignment_id_fkey" FOREIGN KEY ("course_assignment_id") REFERENCES "course_assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_ended_by_fkey" FOREIGN KEY ("ended_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "sessions_started_by_fkey" FOREIGN KEY ("started_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_levels" ADD CONSTRAINT "program_levels_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "program_levels" ADD CONSTRAINT "program_levels_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specialties" ADD CONSTRAINT "specialties_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specialties" ADD CONSTRAINT "specialties_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_class_id_fkey" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "students_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_course_assignment_id_fkey" FOREIGN KEY ("course_assignment_id") REFERENCES "course_assignments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_academic_year_id_fkey" FOREIGN KEY ("academic_year_id") REFERENCES "academic_years"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timetable_slots" ADD CONSTRAINT "timetable_slots_school_id_fkey" FOREIGN KEY ("school_id") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
